config/routes.rb
Rails.application.routes.draw do
  resources :settings
  root 'sessions#create'

  resources :users, :records, :skills

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/scraper', to: 'scraper#index'
  get '/export', to: 'records#export'

  get '/update_experience', to: 'skills#update_experience'
  get '/calculate_form', to: 'skills#calculate_form'
  post '/calculate', to: 'skills#calculate'
  get '/cancel_update/:id', to: 'skills#cancel_update', as: :cancel_update

  get '/edit_password', to: 'users#edit_password'
  post '/update_password', to: 'users#update_password'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def generate_password_token!
    self.reset_password_token = generate_token
    self.reset_password_sent_at = Time.now.utc
    save!
  end

  def password_token_valid?
    (self.reset_password_sent_at + 4.hours) > Time.now.utc
  end

  def reset_password!(password)
    self.reset_password_token = nil
    self.password = password
    save!
  end

  private

  def generate_token
    SecureRandom.hex(10)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :render_login, only: [:edit_password, :update_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit_password

  end

  def update_password
    @user = User.last

    if params[:new_password] == params[:confirm_password]
      @user.password = params[:new_password]
      @user.save!
    end

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_password.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center form-login height-500">
      <p>
        <%= form_tag update_password_path do %>
          <%= password_field_tag :current_password, nil, placeholder: "Current Password", class: "form-control" %>
          <br>

          <%= password_field_tag :new_password, nil, placeholder: "New Password", class: "form-control" %>
          <br>

          <%= password_field_tag :confirm_password, nil, placeholder: "Confirm New Password", class: "form-control" %>
          <br>

          <%= submit_tag "Update", class: "btn btn-primary m-w-150" %>
        <% end %>
      </p>
    </div>
  </div>
</div>