config/routes.rb
Rails.application.routes.draw do
  resources :settings
  root 'sessions#create'

  resources :users, :records, :skills

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/scraper', to: 'scraper#index'
  get '/export', to: 'records#export'

  get '/update_experience', to: 'skills#update_experience'
  get '/calculate_form', to: 'skills#calculate_form'
  post '/calculate', to: 'skills#calculate'
  get '/cancel_update/:id', to: 'skills#cancel_update', as: :cancel_update

  get '/edit_password', to: 'users#edit_password'
  post '/update_password', to: 'users#update_password'

end

app/models/skill.rb
class Skill < ApplicationRecord
  include Filterable

  scope :filter_by_keyword, -> (search_word) {
    where(
      "LOWER(name) like ? OR cast(min as text) like ? OR cast(max as text) like ? OR LOWER(experience) like ?",
      "%#{search_word}%", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%"
    )}
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: %i[ show edit update destroy cancel_update ]

  # GET /skills or /skills.json
  def index
    @skill = Skill.new
    $skills = Skill.filter(params[:search]).reverse
    @skills = Kaminari.paginate_array($skills).page(params[:page]).per(Kaminari.config.default_per_page)
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills or /skills.json
  def create
    @skill = Skill.new(skill_params)
    @skill.save!
  end

  # PATCH/PUT /skills/1 or /skills/1.json
  def update
    @skill.update!(skill_params)
  end

  # DELETE /skills/1 or /skills/1.json
  def destroy
    @skill.destroy!
  end

  def calculate_form
    @skills = Skill.all
  end

  def calculate
    $cost_to_company = Setting.last.cost_to_company
    $bonus = 0.2

    if skill_params[:max].present?
      @skill = nil
      @total = skill_params[:max].to_f + $cost_to_company + (skill_params[:max].to_f * $bonus)
    else
      @skill = Skill.find_by(name: skill_params[:name], experience: skill_params[:experience])
      @total = @skill.present? ? @skill.max + $cost_to_company + (@skill.max * $bonus) : nil
    end
  end

  def update_experience
    @skills = Skill.where("LOWER(name) = ?", params[:name].downcase)
  end

  def cancel_update

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.fetch(:skill, {}).permit(:name, :min, :max, :experience)
    end
end

app/views/skills/_calculated_results.html.erb
<% if @skill.present? %>
  <div class="row m-b-40">
    <div class="col">
      <div class="package_box m-0-a">
        <h3 class="_title">
          <span class="multiplier">
            <%= "Resource Details" %>
          </span>
        </h3>
        <div>
          <%= "Min Salary: " %>
          <span class="multiplier">
            <%= "€" + skill.min.to_s %>
          </span>
        </div>
        <div>
          <%= "Max Salary: " %>
          <span class="multiplier">
            <%= "€" + skill.max.to_s %>
          </span>
        </div>
        <div>
          <%= "Bonus: "  %>
          <span class="multiplier">
            <%= "€" + (skill.max*$bonus).to_s %>
          </span>
        </div>
        <div>
          <%= "Cost to Company: "  %>
          <span class="multiplier">
            <%= "€" + $cost_to_company.to_s %>
          </span>
        </div>
        <div>
          <%= "Total: " %>
          <span class="multiplier">
            <%= "€" + total.to_s %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="row m-b-40">
  <% [{ 2 => "Opal "}, { 2.5 => "Emerald "}, { 3 => "Topaz "}, { 3.5 => "Sapphire "}, { 4 => "Ruby "}, { 4.5 => "Diamond "}].each do |combo| %>
    <% combo.each do |key, value| %>
      <div class="col">
        <div class="package_box m-0-a">
          <h3 class="_title">
            <%= value %>
            <span class="multiplier">
              <%= "(" + key.to_s + "X)" %>
            </span>
          </h3>

          <div class="total_cost">
            <%= '€' + (total * key).to_s %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/skills/_edit_form.html.erb
<%= form_for :skill, url: skills_path(@skill), method: :put, remote: true do |f| %>
<%#= form_for :skill, url: "/skills/#{@skill.id}", method: :put, remote: true do |f| %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <td> <%= @skill.id %> </td>
  <td> <%= f.text_field :name, placeholder: "Skill Name", value: @skill.name %> </td>
  <td> <%= f.number_field :min, placeholder: "Min Salary", value: @skill.min %> </td>
  <td> <%= f.number_field :max, placeholder: "Max Salary", value: @skill.max %> </td>
  <td> <%= f.text_field :experience, placeholder: "Ex: 2-3", value: @skill.experience %> </td>
  <td> <%= f.submit 'Save' %> </td>
<% end %>

app/views/skills/_form.html.erb
<% if @skill.new_record? %>

  <%= form_for :skill, method: :post, remote: true do |f| %>
    <td> <%= @skill.id %> </td>
    <td> <%= f.text_field :name, placeholder: "Skill Name" %> </td>
    <td> <%= f.number_field :min, placeholder: "Min Salary" %> </td>
    <td> <%= f.number_field :max, placeholder: "Max Salary" %> </td>
    <td> <%= f.text_field :experience, placeholder: "Ex: 2-3" %> </td>
    <td>
      <%= f.submit 'Create' %>
    </td>

  <% end %>

<% else %>

  <%= form_for :skill, method: :put, remote: true do |f| %>
    <td> <%= @skill.id %> </td>
    <td> <%= f.text_field :name, placeholder: "Skill Name", class: 'skill_edit_name' %> </td>
    <td> <%= f.number_field :min, placeholder: "Min Salary", class: 'skill_edit_min' %> </td>
    <td> <%= f.number_field :max, placeholder: "Max Salary", class: 'skill_edit_max' %> </td>
    <td> <%= f.text_field :experience, placeholder: "Ex: 2-3", class: 'skill_edit_experience' %> </td>
    <td>
      <%= f.submit 'Save', { class: "edit_skill_button", data_id: "#{@skill.id}", data_url: "#{skill_path}"} %>
      <%= link_to "Cancel", cancel_update_path(@skill), remote: true, class: "cancel"%>
    </td>
  <% end %>

<% end %>

app/views/skills/_row.html.erb
<td><%= skill.id %></td>
<td><%= skill.name %></td>
<td><%= skill.min %></td>
<td><%= skill.max %></td>
<td><%= skill.experience %></td>
<td>
  <%= link_to "Edit", edit_skill_path(skill), remote: true %>
  <%= link_to 'Delete', skill_path(skill), method: :delete, remote: true %>
</td>

app/views/skills/_skill.html.erb
<option value="<%= skill.experience %>"><%= skill.experience %></option>

app/views/skills/_table_row.html.erb
<tr class="table-row-<%=skill.id%>">
  <%= render 'skills/row', skill: skill %>
</tr>

app/views/skills/calculate.js.erb
<% if @total.present? %>
  var results = "<%= j render "skills/calculated_results", total: @total, skill: @skill %>"
  $('.results').html(results).fadeIn('slow');
<% else %>
  var results = "No relevant result found!"
  $('.results').html(results).fadeIn('slow');
<% end %>

$(".form-control").val("");

app/views/skills/calculate_form.html.erb
<div class="table_filters_wrap">
  <div class="container">
    <%= form_for :skill, url: calculate_path, remote: true do |f| %>
      <div class="row m-b-40">
        <h3 class="multiplier">Calculate by Skill & Experience</h3>
      </div>
      <div class="row">
        <div class="col-sm-8 m-0-a">
          <div class="main_inner_search_wrap calculator-form">
            <%= f.label :name, "Resource", class: "m-r-10 m-w-90" %>
            <%= f.select :name, @skills.map(&:name).uniq, {:include_blank => "Select skill"}, class: "skill-select form-control m-r-40" %>

            <%= f.label :experience, "Experience", class: "m-r-10 m-w-90" %>
            <%= f.select :experience, {}, {:include_blank => "Select experience"}, class: "experience-select form-control m-r-40" %>

            <%= f.submit 'Calculate', class: "btn btn-primary m-r-40" %>
          </div>
        </div>
      </div>

      <hr/>

      <div class="row m-b-40">
        <h3 class="multiplier">Calculate by Salary</h3>
      </div>
      <div class="row">
        <div class="col-sm-8 m-0-a">
          <div class="main_inner_search_wrap">
            <%= f.label :max, "Salary", class: "m-r-10 m-w-90" %>
            <%= f.text_field :max, placeholder: "Maximum Salary", class: "form-control m-r-40" %>

            <%= f.submit 'Calculate', class: "btn btn-primary m-r-40" %>
          </div>
        </div>
      </div>
    <% end %>

    <hr class="m-b-40"/>

    <div class="results error_msg"/>
  </div>
</div>

app/views/skills/cancel_update.js.erb
var row = "<%= j render 'skills/row', skill: @skill %>";

$('.table-row-<%=@skill.id%>').removeClass('edit-in-progress').html(row);

app/views/skills/create.js.erb
var skill_row = "<%= j render 'skills/table_row', skill: @skill %>";

//Add newly created table row
$('.table-form-body').after(skill_row).fadeIn('slow');

//Flash new row to bring user's attention
$('.table-row-<%=@skill.id %>').fadeOut(200).fadeIn(400);

//Reset form after new skill is created
$(".table-form-body form")[0].reset();

app/views/skills/destroy.js.erb
$('.table-row-<%=@skill.id%>').fadeOut('slow');

<%# if $skills.size == 0 %>
//  $('.no-skills').css('display', 'block');
<%# end %>

app/views/skills/edit.js.erb
if ($(".cancel").length){
  $(".cancel")[0].click();
}

var editable_row = "<%= j render 'skills/form', skill: @skill %>";

$('.table-row-<%=@skill.id%>').addClass('edit-in-progress').html(editable_row).fadeIn('slow');

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/update_experience.js.erb
<% if @skills.present? %>
  $(".experience-select").empty().append("<%= escape_javascript(render(:partial => @skills)) %>")
<% else %>
  $(".experience-select").empty().append("<option>Select experience</option>")
<% end %>