config/routes.rb
Rails.application.routes.draw do
  resources :settings
  root 'sessions#create'

  resources :users, :records, :skills

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/scraper', to: 'scraper#index'
  get '/export', to: 'records#export'

  get '/update_experience', to: 'skills#update_experience'
  get '/calculate_form', to: 'skills#calculate_form'
  post '/calculate', to: 'skills#calculate'
  get '/cancel_update/:id', to: 'skills#cancel_update', as: :cancel_update

  get '/edit_password', to: 'users#edit_password'
  post '/update_password', to: 'users#update_password'

end

app/models/record.rb
class Record < ApplicationRecord

  # Bulk upload records
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      record_hash = Record.new
      record_hash.dev_name = row[0]
      record_hash.skills = row[1]
      record_hash.save
    end
  end

  def self.scrape(skills)
    # Require open-uri to parse through the urls
    require 'open-uri'

    # Initiate empty array for bulk creation of jobs in database
    records             = []

    # Hard code URLs for both website with empty query parameters
    api_url          = "https://cv.ee/api/v1/vacancies-service/search?limit=20&offset=0&fuzzy=true&isHourlySalary=false&isRemoteWork=false&lang=en&keywords[]="
    site_url         = "https://cv.ee/et/vacancy/"
    credit_info_url  = "https://www.e-krediidiinfo.ee/otsing?&q="

    # Fetch job titles and companies to reduce duplication
    jobs = Job.pluck(:title, :company).map(&:join)

    # Loop through all skills
    skills.each do |skill|
      # Visit url and look for jobs based on specific skill
      content = JSON.parse(URI.parse(api_url + skill).read)

      if content["vacancies"].present?
        # Loop through each job
        content["vacancies"].each do |job|

        # Skip iteration to stop duplication of record, if published date of current job is older than today.
        # That means it must already be in database.
        if jobs.include?(job["positionTitle"] + job["employerName"])
          next
        end

        # Visit second website to fetch credit info for the company
        url = Addressable::URI.parse(credit_info_url + job["employerName"]).display_uri.to_s
        credit_info_page  = Nokogiri::HTML(URI.parse(url).read)

        # If table exists, it means there are multiple results for the company name
        # Extract revenue info if there is a direct hit on company name
        if credit_info_page.at('table.table-search') == nil
          revenue_row     = credit_info_page.at('table').search('tr')[-3].children.text.split("\n").map(&:strip).select(&:present?).last.split(" (perioodil ")
          revenue         = revenue_row.first
          dates           = revenue_row.last.gsub(")","").split(" - ").map(&:to_datetime)
          revenue_period  = (dates.last - dates.first).to_i.to_s + " days"
        else
          # Write logic to do same processing as above for the very first record if there are multiple hits on the company name
        end

        # Create a populated hash to push in records array for bulk creation.
        single_job = {
          skill:          skill,
          title:          job["positionTitle"],
          company_id:     job["employerId"],
          company:        job["employerName"],
          link:           site_url + job["id"].to_s + '/' + job["employerName"].parameterize + '/' + job["positionTitle"].parameterize,
          published_date: job["publishDate"],
          published_type: job["renewedDate"].present? ? "Renewed" : "Published",
          renewed_date:   job["renewedDate"],

          revenue:        revenue || nil,
          revenue_period: revenue_period || nil,
          created_at:     Time.now.utc,
          updated_at:     Time.now.utc
        }

        # Push hash to array
        records.push(single_job)
      end
      end
    end

    Job.insert_all!(records) if records.present?
  end

  def self.export_to_csv(jobs)
    attributes = %w{Title Company Link Published_Date Published_Type Revenue Revenue_Period Skill}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      jobs.each do |job|
        csv << attributes.map{ |attr| job.send(attr.downcase) }
      end
    end
  end
  
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  require "google_sheets_service"

  def new
    @record = Record.new
  end

  def create
    if record_params[:option] == "skill"
      Record.scrape(record_params[:skills])
    elsif record_params[:option] == "sheet"
      extract_skills
      Record.scrape(@skills)
    elsif record_params[:option] == "file"
      Record.import(record_params[:file])
    end
    redirect_to records_path
  end

  def index
    @record = Record.new
    $records = Job.filter(params[:search]).reverse
    @records = Kaminari.paginate_array($records).page(params[:page]).per(Kaminari.config.default_per_page)
  end

  def export
    send_data Record.export_to_csv($records), filename: "records-#{Date.today}.csv"
  end

  private

  def record_params
    record_params = params.fetch(:record, {}).permit(:skills, :option)
    record_params[:skills] = record_params[:skills].split(",") if record_params[:skills].present?

    record_params
  end

  def extract_skills
    spreadsheet_id  = "1t_y1LPrGKrjcOgro1R1bF72iaPBJjJRNAXp0ugK61wE"
    range           = "Sheet1!A3:B"

    service         = GoogleSheetsService.service
    response        = service.get_spreadsheet_values spreadsheet_id, range

    @skills         = response.values.map{|v| v[1].gsub(" ","").split(",")}.flatten.uniq
  end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_filters.html.erb
<div class="table_filters_wrap">
  <div class="container">
    <%= form_tag(records_path, method: :get) do %>
      <div class="row">
        <div class="col-sm-6">
          <div class="main_inner_search_wrap">
            <div class="inner_search_wrap">
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
              <%= submit_tag "Search", class: "btn btn-primary" %>
            </div>
            <%= link_to "Clear Search", records_path, class: "btn btn-danger" %>
          </div>

        </div>
        <div class="col-sm-6">
          <%= link_to "Export to CSV", export_path, class: "btn btn-success m-w-150" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/records/_row.html.erb
<tr>
  <td><%= record.id %></td>
  <td><%= link_to record.title, record.link, target: :_blank %></td>
  <td><%= record.company %></td>
  <td><%= record.published_date %></td>
  <td><%= record.published_type %></td>
  <td><%= record.revenue %></td>
  <td><%= record.revenue_period %></td>
  <td><%= record.skill %></td>
</tr>

app/views/records/_search_options.html.erb
<div class="filters_form_wrap">
  <div class="container">
    <div class="row">
      <div class="col-sm-5">
        <%= form_for @record, url: records_path, method: :post  do |f| %>
          <%= f.hidden_field :option, value: "sheet" %>
          <%= f.button "Search By Google Sheet", type: "submit", class: "btn btn-success" %>
        <% end %>
      </div>
      <div class="col-sm-7">
        <div class="search_by_skills">
          <%= form_for @record, url: records_path, method: :post  do |f| %>
            <%= f.hidden_field :option, value: "skill" %>
            <%= f.text_field :skills, placeholder: "Skills", class: "form-control" %>
            <%= f.button "Search By Skills", type: "submit", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(".loader_wrap").removeClass("loader_show");

  $(document).on('click', 'button[type=submit]', function (){
    $(".loader_wrap").addClass("loader_show");
  });
</script>

app/views/records/_table.html.erb
<div class="scrap_table_wrap">
  <div class="container">
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Company</th>
          <th scope="col">Publish Date</th>
          <th scope="col">Publish Type</th>
          <th scope="col">Revenue</th>
          <th scope="col">Revenue Period</th>
          <th scope="col">Skill</th>
        </tr>
        </thead>
        <tbody>
        <% @records.each.with_index(1) do |record, index| %>
          <%= render 'records/row', record: record, i: index %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<%= render 'search_options' %>

<%- if @records.present? %>
  <%= render 'filters' %>
  <%= render 'table' %>
  <div class="container">
    <div class="pagination_wrap">
      <%= paginate @records %>
    </div>
  </div>

<% else %>
  <%= render 'filters' %>
  <div class="text-center fw-bold"> No Record Found! </div>
<% end %>

app/views/records/new.html.erb
<div class="jumbotron text-center">
  <h1>Jobs Scraper</h1>
</div>

<div class="container p-5">

  <div class="row">
    <div class="col-lg-12 text-center form-login">
      <p>
        <%= form_for @record, url: records_path do |f| %>
          <%= f.file_field :file, placeholder: "Upload CSV", class: 'form-control form-control-file', required: true %>
          <br>
          <%= f.button "Upload CSV", type: "submit", class: "form-control btn btn-primary" %>
        <% end %>
      </p>
    </div>
  </div>

  <br><hr><br>

  <div>
    <div class="col-lg-12 text-center form-login">
      <p>
        <%= form_for @record, url: records_path do |f| %>
          <%= f.text_field :skills, placeholder: "Skills", class: "form-control" %>
          <br>
          <%= f.button "Submit", type: "submit", class: "form-control btn btn-primary" %>
        <% end %>
      </p>
    </div>
  </div>

</div>