config/routes.rb
Rails.application.routes.draw do
  resources :settings
  root 'sessions#create'

  resources :users, :records, :skills

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/scraper', to: 'scraper#index'
  get '/export', to: 'records#export'

  get '/update_experience', to: 'skills#update_experience'
  get '/calculate_form', to: 'skills#calculate_form'
  post '/calculate', to: 'skills#calculate'
  get '/cancel_update/:id', to: 'skills#cancel_update', as: :cancel_update

  get '/edit_password', to: 'users#edit_password'
  post '/update_password', to: 'users#update_password'

end

app/views/layouts/_navigation.html.erb
<nav class="main_header">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <%= link_to "Opti-Scraper", logged_in? ? records_path : root_path, class: 'navbar-brand' %>
      </div>
      <% if logged_in? %>
        <div class="col-sm-8">
          <div class="main_menu_wrap">
            <ul>
              <li class= "<%= current_page?('/records') ? 'active' : '' %>"><%= link_to 'Scraper', records_path %></li>
              <li class= "<%= current_page?('/skills') ? 'active' : '' %>"><%= link_to 'Skills', skills_path, class: '' %></li>
              <li class= "<%= current_page?('/calculate_form') ? 'active' : '' %>"><%= link_to 'Calculator', calculate_form_path, class: '' %></li>
              <li class= "<%= current_page?('/settings/1/edit') ? 'active' : '' %>"><%= link_to 'Settings', edit_setting_path(1), class: '' %></li>
              <li><%= link_to "Logout", logout_path, class: "" %></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_spinner.html.erb
<div class="loader_wrap">
  <div class="spinner">
    <div class="bounce1"></div>
    <div class="bounce2"></div>
    <div class="bounce3"></div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Opti-Scrape</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('Optimyse.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/spinner' %>
    <%= yield %>
  </body>
</html>